# Default values for eureka-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# pod运行数量
replicaCount: 1

image:
  # 镜像库地址
  repository: registry.cn-hangzhou.aliyuncs.com/choerodon-framework/eureka-server
  # 镜像拉取策略
  pullPolicy: IfNotPresent

env:
  open:
    SECURITY_BASIC_ENABLED: false

deployment:
  # 服务管理端口
  managementPort: 8001

service:
  # 是否创建k8s service
  enabled: false
  # service类型
  type: ClusterIP
  # service端口
  port: 8000
  # service名称
  name: eureka-server

ingress:
  # 是否创建k8s ingress
  enabled: false
  # 服务域名地址
  host: eureka.choerodon.com.cn

metrics:
  # 收集应用的指标数据路径
  path: /prometheus
  # 性能指标应用分组
  group: spring-boot

logs:
  # 日志收集格式
  parser: spring-boot

resources:
  # k8s中容器能使用资源的资源最大值
  limits:
    # cpu: 100m
    memory: 2Gi
  # k8s中容器使用的最小资源需求
  requests:
    # cpu: 100m
    memory: 1Gi